name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ created ]

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'
      - run: composer validate --strict --no-check-lock

  check_code_style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'

      - name: Install dependencies
        run: composer update

      - run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --show-progress=dots

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'
      - name: Install dependencies
        run: composer update
      - run: ./vendor/bin/phpstan analyze

  tests:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        composer-flags: [ "" ]
        symfony-version: [ "" ]
        include:
          - php: 8.1
            symfony-version: '^5.4'
          - php: 8.1
            symfony-version: '^6.4'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-file: "development"
          coverage: none

      - name: Update Symfony version
        if: matrix.symfony-version != ''
        run: composer require --no-update "symfony/symfony:${{ matrix.symfony-version }}"

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }}

      - name: Run tests (phpunit)
        run: ./vendor/bin/phpunit
