name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ created ]

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'

      - run: composer validate --strict --no-check-lock

  check_code:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'

      - run: composer update --ansi --no-progress

      - run: composer lint

  tests:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        composer-flags: [ "" ]
        include:
          - php: 8.1
            composer-flags: "--with=symfony/yaml:^5.4"
          - php: 8.1
            composer-flags: "--with=symfony/yaml:^6.4"
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-file: "development"
          coverage: "xdebug"

      - run: composer update ${{ matrix.composer-flags }} --ansi --no-progress

      - run: composer test -- --coverage-clover=coverage.xml --log-junit junit.xml --testdox

      - uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: php${{ matrix.php }}${{ matrix.composer-flags }}

      - uses: codecov/test-results-action@v1
