name: Build

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]
        composer-flags: [ "" ]
        symfony-version: [ "" ]
        include:
          -   php: 5.6
              composer-flags: '--prefer-lowest'
          -   php: 5.6
              symfony-version: '2.3.*'
          -   php: 5.6
              symfony-version: '2.7.*'
          -   php: 5.6
              symfony-version: '2.8.*'
          -   php: 7.1
              symfony-version: '3.*'

    steps:
      -   uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "${{ matrix.php }}"
            coverage: none

      -   name: Update Symfony version
          if: matrix.symfony-version != ''
          run: composer require --no-update "symfony/symfony:${{ matrix.symfony-version }}"

      -   name: Install dependencies
          run: composer update ${{ matrix.composer-flags }}

      -   name: Run tests (phpunit)
          run: ./vendor/bin/phpunit
