name: Lint Actions

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'

jobs:
  check_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-actionlint@v1
        with:
          fail_level: 'any'
          filter_mode: 'nofilter'
