name: Update Composer

on:
  schedule:
    -   cron: '0 7 * * *'
  pull_request:
    branches:
      - master

jobs:
  check-new-tags:
    runs-on: ubuntu-latest
    name: Check for new tags
    steps:
      -   uses: actions/checkout@master
      -   run: bin/update_cucumber
